UNI-37: implement sign out button
Siyer2/uni-connector pull request #20
Opened 2022-10-24 04:48 UTC by vivianchengg

2022-10-27 14:54 UTC, Siyer2 requested changes
Almost there with it Vivian!

2022-10-27 14:54 UTC, Siyer2 commented on frontend/src/pages/Chats.tsx
> +      <ButtonAppBar />
This TopAppBar component will be used across many different pages e.g. imagine if we add a page to update a user's faculty. So what we need to do is move the ButtonAppBar to its own file in the components folder.

2022-10-27 14:54 UTC, Siyer2 commented on frontend/src/pages/Chats.tsx
> +    </AppBar>
When we move this to the components folder, we still need a way for the chats page to display all the chat information below the AppBar. This is how we can do it - we pass the chat information as a 'children' prop to the AppBar. Our ultimate goal is that the chats page looks something like this:
```
export const Chats = () => {
  return (
    <TopAppBar>
      <div>chat messages here etc etc</div>
    </TopAppBar>
  );
};
```

HINT: in the new TopAppBar component, you'll need to be able to pass children elements into it. 
HINT2: Check out how I've done it in the [PageLayout component](https://github.com/Siyer2/uni-connector/blob/73a654e148228e1595d7c1c64cfe4d853136406c/frontend/src/components/PageLayout.tsx#L17).

2022-11-14 16:21 UTC, vivianchengg commented on frontend/src/pages/Chats.tsx
> +    </AppBar>
got it! Please review changes!

2022-11-15 03:11 UTC, Siyer2 approved these changes
Nice!

2022-11-15 03:11 UTC, merged